// <auto-generated />
using System;
using DispensAR.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DispensAR.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260907144408_InitialMultitenancy")]
    partial class InitialMultitenancy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DispensAR.Api.Data.Branch", b =>
                {
                    b.Property<string>("TenantId")
                        .HasMaxLength(63)
                        .HasColumnType("nvarchar(63)");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.HasKey("TenantId", "Id");

                    b.ToTable("Branches");

                    b.HasData(
                        new
                        {
                            TenantId = "demo",
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Name = "Sucursal Centro"
                        },
                        new
                        {
                            TenantId = "demo",
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Name = "Sucursal Norte"
                        },
                        new
                        {
                            TenantId = "acme",
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            Name = "Sucursal Sur"
                        });
                });

            modelBuilder.Entity("DispensAR.Api.Data.Organization", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(63)
                        .HasColumnType("nvarchar(63)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.HasKey("Id");

                    b.ToTable("Organizations");

                    b.HasData(
                        new
                        {
                            Id = "demo",
                            Name = "DispensAR Demo"
                        },
                        new
                        {
                            Id = "acme",
                            Name = "ACME"
                        });
                });

            modelBuilder.Entity("DispensAR.Api.Data.OrganizationUser", b =>
                {
                    b.Property<string>("TenantId")
                        .HasMaxLength(63)
                        .HasColumnType("nvarchar(63)");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.HasKey("TenantId", "Id");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            TenantId = "demo",
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            DisplayName = "Usuario Demo",
                            Email = "demo@example.test"
                        },
                        new
                        {
                            TenantId = "acme",
                            Id = new Guid("40000000-0000-0000-0000-000000000001"),
                            DisplayName = "Usuario ACME",
                            Email = "acme@example.test"
                        });
                });

            modelBuilder.Entity("DispensAR.Api.Data.Branch", b =>
                {
                    b.HasOne("DispensAR.Api.Data.Organization", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DispensAR.Api.Data.OrganizationUser", b =>
                {
                    b.HasOne("DispensAR.Api.Data.Organization", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
