// <auto-generated />
using System;
using DispensAR.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DispensAR.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence<int>("TenantNumbers")
                .StartsAt(3L);

            modelBuilder.Entity("DispensAR.Api.Auth.Account", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("EsAdministradorPlataforma")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("TenantId");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("DispensAR.Api.Dashboard.DashboardWidget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Tamano")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TipoIndicador")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("WidgetsDashboard", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Codigo = "pacientes_activos",
                            Descripcion = "Pacientes activos",
                            Tamano = "normal",
                            TipoIndicador = "pacientes_activos",
                            Version = new byte[0]
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Codigo = "cantidad_dispensada",
                            Descripcion = "Cantidad dispensada",
                            Tamano = "normal",
                            TipoIndicador = "cantidad_dispensada",
                            Version = new byte[0]
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Codigo = "stock_disponible",
                            Descripcion = "Stock disponible",
                            Tamano = "normal",
                            TipoIndicador = "stock_disponible",
                            Version = new byte[0]
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Codigo = "sucursales",
                            Descripcion = "Sucursales",
                            Tamano = "normal",
                            TipoIndicador = "sucursales",
                            Version = new byte[0]
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Codigo = "alertas",
                            Descripcion = "Alertas",
                            Tamano = "ancho",
                            TipoIndicador = "alertas",
                            Version = new byte[0]
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            Codigo = "ultimas_dispensaciones",
                            Descripcion = "Últimas dispensaciones",
                            Tamano = "ancho",
                            TipoIndicador = "ultimas_dispensaciones",
                            Version = new byte[0]
                        });
                });

            modelBuilder.Entity("DispensAR.Api.Dashboard.OrganizationWidget", b =>
                {
                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<int>("WidgetId")
                        .HasColumnType("int");

                    b.Property<bool>("Habilitado")
                        .HasColumnType("bit");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("TenantId", "WidgetId");

                    b.HasIndex("WidgetId");

                    b.ToTable("WidgetsDashboardOrganizaciones", (string)null);

                    b.HasData(
                        new
                        {
                            TenantId = 1,
                            WidgetId = 1,
                            Habilitado = true,
                            Orden = 0,
                            Version = new byte[0]
                        },
                        new
                        {
                            TenantId = 2,
                            WidgetId = 1,
                            Habilitado = true,
                            Orden = 0,
                            Version = new byte[0]
                        },
                        new
                        {
                            TenantId = 1,
                            WidgetId = 2,
                            Habilitado = true,
                            Orden = 1,
                            Version = new byte[0]
                        },
                        new
                        {
                            TenantId = 2,
                            WidgetId = 2,
                            Habilitado = true,
                            Orden = 1,
                            Version = new byte[0]
                        },
                        new
                        {
                            TenantId = 1,
                            WidgetId = 3,
                            Habilitado = true,
                            Orden = 2,
                            Version = new byte[0]
                        },
                        new
                        {
                            TenantId = 2,
                            WidgetId = 3,
                            Habilitado = false,
                            Orden = 2,
                            Version = new byte[0]
                        },
                        new
                        {
                            TenantId = 1,
                            WidgetId = 4,
                            Habilitado = true,
                            Orden = 3,
                            Version = new byte[0]
                        },
                        new
                        {
                            TenantId = 2,
                            WidgetId = 4,
                            Habilitado = true,
                            Orden = 3,
                            Version = new byte[0]
                        },
                        new
                        {
                            TenantId = 1,
                            WidgetId = 5,
                            Habilitado = false,
                            Orden = 4,
                            Version = new byte[0]
                        },
                        new
                        {
                            TenantId = 2,
                            WidgetId = 5,
                            Habilitado = false,
                            Orden = 4,
                            Version = new byte[0]
                        },
                        new
                        {
                            TenantId = 1,
                            WidgetId = 6,
                            Habilitado = false,
                            Orden = 5,
                            Version = new byte[0]
                        },
                        new
                        {
                            TenantId = 2,
                            WidgetId = 6,
                            Habilitado = false,
                            Orden = 5,
                            Version = new byte[0]
                        });
                });

            modelBuilder.Entity("DispensAR.Api.Data.Branch", b =>
                {
                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.HasKey("TenantId", "Id");

                    b.ToTable("Sucursales", (string)null);

                    b.HasData(
                        new
                        {
                            TenantId = 1,
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Name = "Sucursal Centro"
                        },
                        new
                        {
                            TenantId = 1,
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Name = "Sucursal Norte"
                        },
                        new
                        {
                            TenantId = 2,
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            Name = "Sucursal Sur"
                        });
                });

            modelBuilder.Entity("DispensAR.Api.Data.Lote", b =>
                {
                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateOnly?>("FechaVencimiento")
                        .HasColumnType("date");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("TenantId", "Id");

                    b.HasIndex("TenantId", "ProductoId", "Codigo")
                        .IsUnique();

                    b.ToTable("Lotes", (string)null);
                });

            modelBuilder.Entity("DispensAR.Api.Data.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR [TenantNumbers]");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.HasKey("Id");

                    b.ToTable("Organizaciones", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "DispensAR Demo"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "ACME"
                        });
                });

            modelBuilder.Entity("DispensAR.Api.Data.OrganizationUser", b =>
                {
                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.HasKey("TenantId", "Id");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique();

                    b.ToTable("PerfilesUsuarios", (string)null);

                    b.HasData(
                        new
                        {
                            TenantId = 1,
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            DisplayName = "Usuario Demo",
                            Email = "demo@example.test"
                        },
                        new
                        {
                            TenantId = 2,
                            Id = new Guid("40000000-0000-0000-0000-000000000001"),
                            DisplayName = "Usuario ACME",
                            Email = "acme@example.test"
                        });
                });

            modelBuilder.Entity("DispensAR.Api.Data.Paciente", b =>
                {
                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<DateOnly?>("AutorizacionHasta")
                        .HasColumnType("date");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .IsFixedLength(false);

                    b.Property<int>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateOnly?>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("TenantId", "Id");

                    b.HasIndex("TenantId", "Dni")
                        .IsUnique();

                    b.ToTable("Pacientes", (string)null);
                });

            modelBuilder.Entity("DispensAR.Api.Data.Producto", b =>
                {
                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("TenantId", "Id");

                    b.HasIndex("TenantId", "Codigo")
                        .IsUnique();

                    b.ToTable("Productos", (string)null);
                });

            modelBuilder.Entity("DispensAR.Api.Identidad.IdentidadVisual", b =>
                {
                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<string>("ColorPrimario")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("ColorSecundario")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("ColorSidebarFondo")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("ColorSidebarTexto")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("LogoCompactoContenido")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("LogoCompactoRuta")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("LogoPrincipalContenido")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("LogoPrincipalRuta")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("TenantId");

                    b.ToTable("IdentidadesVisuales", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AtributosUsuarios", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AccesosExternosUsuarios", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("TokensUsuarios", (string)null);
                });

            modelBuilder.Entity("DispensAR.Api.Auth.Account", b =>
                {
                    b.HasOne("DispensAR.Api.Data.Organization", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DispensAR.Api.Dashboard.OrganizationWidget", b =>
                {
                    b.HasOne("DispensAR.Api.Data.Organization", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DispensAR.Api.Dashboard.DashboardWidget", null)
                        .WithMany()
                        .HasForeignKey("WidgetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DispensAR.Api.Data.Branch", b =>
                {
                    b.HasOne("DispensAR.Api.Data.Organization", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DispensAR.Api.Data.Lote", b =>
                {
                    b.HasOne("DispensAR.Api.Data.Producto", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DispensAR.Api.Data.OrganizationUser", b =>
                {
                    b.HasOne("DispensAR.Api.Data.Organization", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DispensAR.Api.Data.Paciente", b =>
                {
                    b.HasOne("DispensAR.Api.Data.Organization", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DispensAR.Api.Data.Producto", b =>
                {
                    b.HasOne("DispensAR.Api.Data.Organization", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DispensAR.Api.Identidad.IdentidadVisual", b =>
                {
                    b.HasOne("DispensAR.Api.Data.Organization", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DispensAR.Api.Auth.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DispensAR.Api.Auth.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DispensAR.Api.Auth.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
